# Generated by Django 6.0 on 2026-01-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrator'), ('user', 'Regular User'), ('moderator', 'Moderator')], default='user', max_length=20),
        ),
    ]
