# Generated by Django 6.0 on 2026-01-05 17:47

import Authenication.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenication', '0002_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('course_file', models.FileField(help_text='Upload PDF or DOCX file (max 50MB)', upload_to=Authenication.models.course_upload_path, validators=[Authenication.models.validate_pdf_or_docx])),
                ('file_size', models.PositiveIntegerField(default=0, editable=False)),
                ('file_type', models.CharField(editable=False, max_length=10)),
                ('total_pages', models.PositiveIntegerField(default=0, editable=False)),
                ('is_public', models.BooleanField(default=False)),
                ('allow_comments', models.BooleanField(default=True)),
                ('enable_progress_tracking', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('total_lessons', models.PositiveIntegerField(default=0, editable=False)),
                ('total_enrollments', models.PositiveIntegerField(default=0, editable=False)),
                ('average_rating', models.FloatField(default=0.0, editable=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', to=settings.AUTH_USER_MODEL, verbose_name='Course Creator')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rating from 1 to 5 stars')),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Authenication.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Rating',
                'verbose_name_plural': 'Course Ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('page_number', models.PositiveIntegerField(help_text='Page number in the document')),
                ('page_range', models.CharField(blank=True, help_text='Page range (e.g., "1-5" or "Chapter 1")', max_length=50)),
                ('estimated_duration', models.PositiveIntegerField(default=0, help_text='Estimated duration in minutes')),
                ('lesson_file', models.FileField(blank=True, help_text='Optional supplementary file for this lesson', null=True, upload_to=Authenication.models.lesson_upload_path, validators=[Authenication.models.validate_pdf_or_docx])),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of lesson in the course')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='Authenication.course')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['order', 'page_number'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_page', models.PositiveIntegerField(default=1)),
                ('pages_completed', models.PositiveIntegerField(default=0)),
                ('total_pages_viewed', models.PositiveIntegerField(default=0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('bookmarked_pages', models.JSONField(default=list, help_text='List of bookmarked page numbers')),
                ('notes', models.JSONField(default=dict, help_text='Notes for specific pages: {"page_number": "note_text"}')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='Authenication.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('current_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_enrollments', to='Authenication.lesson')),
            ],
            options={
                'verbose_name': 'Course Enrollment',
                'verbose_name_plural': 'Course Enrollments',
                'ordering': ['-last_accessed'],
            },
        ),
        migrations.CreateModel(
            name='UserProgressLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('page_view', 'Page View'), ('quiz_complete', 'Quiz Completed'), ('bookmark', 'Bookmark Added'), ('note_added', 'Note Added'), ('course_complete', 'Course Completed')], max_length=50)),
                ('time_spent', models.PositiveIntegerField(default=0, help_text='Time spent in seconds')),
                ('metadata', models.JSONField(default=dict, help_text='Additional data about the action')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='Authenication.courseenrollment')),
            ],
            options={
                'verbose_name': 'User Progress Log',
                'verbose_name_plural': 'User Progress Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='Authenicati_slug_0ac874_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['creator', 'created_at'], name='Authenicati_creator_05e4e4_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_public', 'published_at'], name='Authenicati_is_publ_e88880_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courserating',
            unique_together={('user', 'course')},
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'order'], name='Authenicati_course__5c8f5f_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'page_number'], name='Authenicati_course__8f484e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('course', 'page_number')},
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['user', 'course'], name='Authenicati_user_id_7324c0_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['user', 'last_accessed'], name='Authenicati_user_id_228faf_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['course', 'completed_at'], name='Authenicati_course__3c0bb5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together={('user', 'course')},
        ),
        migrations.AddIndex(
            model_name='userprogresslog',
            index=models.Index(fields=['enrollment', 'created_at'], name='Authenicati_enrollm_c69f77_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogresslog',
            index=models.Index(fields=['action', 'created_at'], name='Authenicati_action_1afa97_idx'),
        ),
    ]
