# Generated by Django 6.0 on 2026-01-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenication', '0003_course_courserating_lesson_courseenrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='User biography or description', max_length=500, null=True),
        ),
    ]
